spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

  mail:
    host: smtp.resend.com
    port: 465
    username: resend
    password: ${RESEND_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true

notification:
  email:
    from: ${MAIL_FROM}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: WARN
    com.whatsuphouse: INFO
